plugins {
id 'com.android.application'
}
android {
namespace 'com.ping.keepalive'
compileSdk 34
defaultConfig {
applicationId "com.ping.keepalive"
minSdk 24
targetSdk 34
versionCode 1
versionName "2.0-NDK"
externalNativeBuild {
cmake {
cppFlags ""
cFlags "-std=c99"
}
}
}
buildTypes {
release {
minifyEnabled true
proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
}
}
externalNativeBuild {
cmake {
path "src/main/cpp/CMakeLists.txt"
version "3.22.1+"
}
}
compileOptions {
sourceCompatibility JavaVersion.VERSION_1_8
targetCompatibility JavaVersion.VERSION_1_8
}
}
dependencies {
// 100% හිස්! කිසිම අමතර Library එකක් මෙහි නැත.
}
